name: test

on: [push]
jobs:
  test:
    env:
      POETRY_VERSION: "1.4.0"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Try loading the Poetry installation from cache
      - name: Load cached Poetry installation
        id: cached-poetry-installation
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: ${{ runner.os }}-dotlocal-dir-poetry${{ env.POETRY_VERSION }}-py${{ matrix.python-version }}
      # Install Poetry if the ~/.local cache does not exist
      - name: Install Poetry
        if: steps.cached-poetry-installation.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      # Try loading Poetry venv from cache
      - name: Load cached Poetry environment
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-venv-py${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      # Install dependencies if cache load failed
      - name: Install dependencies with poetry
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install
      - name: Lint with ruff
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          poetry run ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
          # Default set of ruff rules with GitHub Annotations
          poetry run ruff --format=github --target-version=py310 .
      - name: Static type checking with mypy
        run: |
          poetry run mypy plantuml_sequence
      - name: Test with pytest
        run: |
          poetry run pytest --cov
