name: test

on: [push]
jobs:
  test:
    env:
      UV_VERSION: "0.8.22"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
      - name: Install the dependencies
        run: uv sync --locked --all-extras --dev
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check format
        run: uv run ruff format --check .
      - name: Lint with ruff
        run: uv run ruff check --output-format github .
      - name: Static type checking with mypy
        run: uv run mypy plantuml_sequence
      - name: Test with pytest
        run: uv run pytest --cov
